dtb-$(CONFIG_MACH_EXYNOS7904_M30LTE_SWA_OPEN) := \
	exynos7904-m30lte_swa_open_00.dtb \
	exynos7904-m30lte_swa_open_01.dtb \
	exynos7904-m30lte_swa_open_03.dtb \
	exynos7904-m30lte_swa_open_04.dtb

always            := $(dtb-y) $(dtbo-y)
clean-files       := *.dtb*
